// Connecticut high schools — public, magnet, technical, and selected private.
// Used by the SchoolPicker autocomplete in onboarding and student profiles.

export const CT_HIGH_SCHOOLS: string[] = [
  // Hartford County
  "Avon High School",
  "Berlin High School",
  "Bloomfield High School",
  "Bristol Central High School",
  "Bristol Eastern High School",
  "Bulkeley High School (Hartford)",
  "Canton High School",
  "Conard High School (West Hartford)",
  "East Catholic High School",
  "East Granby High School",
  "East Hartford High School",
  "East Windsor High School",
  "Ellington High School",
  "Enfield High School",
  "Farmington High School",
  "Glastonbury High School",
  "Granby Memorial High School",
  "Hall High School (West Hartford)",
  "Hartford Public High School",
  "Lewis S. Mills High School",
  "Manchester High School",
  "Maloney High School (Meriden)",
  "Newington High School",
  "Plainville High School",
  "Platt High School (Meriden)",
  "Rocky Hill High School",
  "Simsbury High School",
  "Southington High School",
  "South Windsor High School",
  "Suffield High School",
  "Tolland High School",
  "Wethersfield High School",
  "Windsor High School",
  "Windsor Locks High School",

  // New Haven County
  "Amity Regional High School",
  "Branford High School",
  "Cheshire High School",
  "Cross High School (New Haven)",
  "Daniel Hand High School (Madison)",
  "East Haven High School",
  "Foran High School (Milford)",
  "Guilford High School",
  "Hamden High School",
  "Hillhouse High School (New Haven)",
  "Jonathan Law High School (Milford)",
  "Lyman Hall High School (Wallingford)",
  "Mark T. Sheehan High School (Wallingford)",
  "Naugatuck High School",
  "North Branford High School",
  "North Haven High School",
  "Oxford High School",
  "Sacred Heart Academy",
  "Seymour High School",
  "Shelton High School",
  "Sheehan High School",
  "Wilbur Cross High School",
  "Woodland Regional High School",

  // Fairfield County
  "Bassick High School (Bridgeport)",
  "Brien McMahon High School (Norwalk)",
  "Bridgeport Central High School",
  "Brookfield High School",
  "Danbury High School",
  "Darien High School",
  "Fairfield Ludlowe High School",
  "Fairfield Warde High School",
  "Greenwich High School",
  "Harding High School (Bridgeport)",
  "Joel Barlow High School",
  "New Canaan High School",
  "New Fairfield High School",
  "Newtown High School",
  "Norwalk High School",
  "Pomperaug High School",
  "Ridgefield High School",
  "Staples High School (Westport)",
  "Stamford High School",
  "Stratford High School",
  "Trumbull High School",
  "Weston High School",
  "Westhill High School (Stamford)",
  "Wilton High School",

  // Litchfield County
  "Litchfield High School",
  "Northwestern Regional High School",
  "Nonnewaug High School",
  "Shepaug Valley School",
  "Torrington High School",
  "Wamogo Regional High School",
  "Watertown High School",
  "Wolcott High School",

  // Middlesex County
  "Coginchaug Regional High School",
  "Cromwell High School",
  "Haddam-Killingworth High School",
  "Middletown High School",
  "Old Saybrook High School",
  "Portland High School",
  "Valley Regional High School",
  "Vinal Technical High School (Middletown)",
  "Westbrook High School",
  "Xavier High School",

  // New London County
  "Bacon Academy",
  "East Lyme High School",
  "Fitch Senior High School (Groton)",
  "Griswold High School",
  "Killingly High School",
  "Ledyard High School",
  "Lyme-Old Lyme High School",
  "Montville High School",
  "New London High School",
  "Norwich Free Academy",
  "Norwich Technical High School",
  "Plainfield High School",
  "Stonington High School",
  "Waterford High School",
  "Wheeler High School (North Stonington)",
  "Windham High School",

  // Tolland County
  "E.O. Smith High School",
  "RHAM High School",
  "Rockville High School (Vernon)",
  "Stafford High School",
  "Tourtellotte Memorial High School",

  // Windham County
  "Putnam High School",
  "Quinebaug Valley Middle College",
  "Tourtellotte Memorial High School",
  "Woodstock Academy",

  // CT Technical Education System (CTECS)
  "A.I. Prince Technical High School (Hartford)",
  "Abbott Technical High School (Danbury)",
  "Bullard-Havens Technical High School (Bridgeport)",
  "E.C. Goodwin Technical High School (New Britain)",
  "Eli Whitney Technical High School (Hamden)",
  "Emmett O'Brien Technical High School (Ansonia)",
  "Ella T. Grasso Technical High School (Groton)",
  "H.C. Wilcox Technical High School (Meriden)",
  "Henry Abbott Technical High School (Danbury)",
  "Howell Cheney Technical High School (Manchester)",
  "J.M. Wright Technical High School (Stamford)",
  "Kaynor Technical High School (Waterbury)",
  "Norwich Technical High School",
  "Oliver Wolcott Technical High School (Torrington)",
  "Platt Technical High School (Milford)",
  "Vinal Technical High School (Middletown)",
  "Windham Technical High School (Willimantic)",

  // Magnet & charter / interdistrict
  "Achievement First Hartford High School",
  "Capital Preparatory Magnet School",
  "Classical Magnet School (Hartford)",
  "Cooperative Arts & Humanities High School (New Haven)",
  "ESUMS — Engineering & Science University Magnet School",
  "Greater Hartford Academy of the Arts",
  "High School Inc. (Hartford)",
  "Hartford Magnet Trinity College Academy",
  "Marine Science Magnet High School (Groton)",
  "Metropolitan Business Academy",
  "Pathways Academy of Technology & Design",
  "Public Safety Academy (Bridgeport)",
  "Sound School (New Haven)",
  "Sport and Medical Sciences Academy",
  "University High School of Science and Engineering",

  // Private / parochial
  "Avon Old Farms School",
  "Cheshire Academy",
  "Choate Rosemary Hall",
  "Hopkins School",
  "Kingswood Oxford School",
  "Loomis Chaffee School",
  "Miss Porter's School",
  "Notre Dame High School (Fairfield)",
  "Notre Dame High School (West Haven)",
  "Pomfret School",
  "South Kent School",
  "St. Joseph High School (Trumbull)",
  "St. Paul Catholic High School (Bristol)",
  "Suffield Academy",
  "Taft School",
  "Westover School",
  "Wilbraham & Monson Academy",
  "Wooster School",
];

export const SCHOOL_SENTINELS = {
  HOME_SCHOOLED: "Home Schooled",
  OTHER: "Other",
  NOT_LISTED: "Not Listed",
  PREFER_NOT: "Prefer Not to Say",
} as const;
