/**
 * Pathway Report v2 schema additions.
 *
 * All fields are additive and OPTIONAL — existing v1 reports keep
 * rendering unchanged. New reports generated by `regeneratePathwayReport`
 * populate `schema_version = 2` plus the v2 fields below.
 */
import { z } from "zod";

export const SourceKind = z.enum([
  "profile",
  "student_voice",
  "iep_doc",
  "iep_extraction",
  "goal",
  "readiness",
  "action_item",
  "meeting_prep",
  "saved_resource",
  "partner_match",
  "family_priority",
  "educator_input",
]);
export type SourceKind = z.infer<typeof SourceKind>;

export const SourceRef = z.object({
  kind: SourceKind,
  id: z.string().optional(),
  label: z.string().trim().min(1).max(240),
});
export type SourceRef = z.infer<typeof SourceRef>;

const OwnerRole = z.enum([
  "student",
  "family",
  "case_manager",
  "educator",
  "school_team",
  "partner",
  "outside_provider",
]);
export type OwnerRole = z.infer<typeof OwnerRole>;

export const PillarRec = z.object({
  title: z.string().trim().min(1).max(160),
  summary: z.string().trim().min(1).max(800),
  why: z.string().trim().min(1).max(800),
  sources: z.array(SourceRef).min(1).max(8),
  next_action: z.string().trim().min(1).max(400),
  owner_role: OwnerRole,
  discuss_at_next_meeting: z.boolean(),
  related_goal_id: z.string().optional(),
  timeframe: z.enum(["30_day", "90_day", "6_month", "1_year"]).optional(),
});
export type PillarRec = z.infer<typeof PillarRec>;

export const ResourceMatch = z.object({
  title: z.string().trim().min(1).max(200),
  url: z.string().trim().max(800).optional(),
  resource_id: z.string().uuid().optional(),
  summary: z.string().trim().max(600).optional(),
  why: z.string().trim().min(1).max(600),
  sources: z.array(SourceRef).min(1).max(6),
  next_action: z.string().trim().min(1).max(300),
  owner_role: OwnerRole,
});
export type ResourceMatch = z.infer<typeof ResourceMatch>;

export const PartnerMatch = z.object({
  title: z.string().trim().min(1).max(200),
  organization: z.string().trim().max(200).optional(),
  url: z.string().trim().max(800).optional(),
  opportunity_id: z.string().uuid().optional(),
  partner_id: z.string().uuid().optional(),
  why: z.string().trim().min(1).max(600),
  sources: z.array(SourceRef).min(1).max(6),
  next_action: z.string().trim().min(1).max(300),
  owner_role: OwnerRole,
  readiness_level: z
    .enum(["emerging", "developing", "progressing", "ready"])
    .optional(),
});
export type PartnerMatch = z.infer<typeof PartnerMatch>;

export const MissingInfo = z.object({
  topic: z.string().trim().min(1).max(200),
  why_it_matters: z.string().trim().min(1).max(500),
  how_to_collect: z.string().trim().min(1).max(400),
  owner_role: OwnerRole,
  blocks_section: z.string().trim().max(80).optional(),
});
export type MissingInfo = z.infer<typeof MissingInfo>;

export const Horizons = z.object({
  thirty_day: z.array(z.string().trim().min(1).max(300)).min(1).max(8),
  ninety_day: z.array(z.string().trim().min(1).max(300)).min(1).max(8),
  six_month: z.array(z.string().trim().min(1).max(300)).min(1).max(8),
  one_year: z.array(z.string().trim().min(1).max(300)).min(1).max(8),
});
export type Horizons = z.infer<typeof Horizons>;

export const ActionPlan = z.object({
  intro: z.string().trim().max(600).optional(),
  horizons: Horizons,
});
export type ActionPlan = z.infer<typeof ActionPlan>;

export const IepPlanSummary = z.object({
  source_doc_ids: z.array(z.string().uuid()).max(8),
  plan_date_start: z.string().trim().max(40).optional(),
  plan_date_end: z.string().trim().max(40).optional(),
  present_levels: z.string().trim().max(2000).optional(),
  transition_goals: z
    .array(
      z.object({
        area: z.string().trim().min(1).max(120),
        goal_text: z.string().trim().min(1).max(800),
        plain_language: z.string().trim().min(1).max(800),
        related_services: z.array(z.string()).max(8).optional(),
      }),
    )
    .max(20),
  accommodations: z.array(z.string().trim().min(1).max(200)).max(20),
  services: z.array(z.string().trim().min(1).max(200)).max(20),
  caveats: z
    .string()
    .trim()
    .max(600)
    .describe("Caveats about AI-extracted IEP data; e.g. 'extracted from upload, please verify'.")
    .optional(),
});
export type IepPlanSummary = z.infer<typeof IepPlanSummary>;

export const SectionCopy = z.record(z.string(), z.string().trim().max(800));
export type SectionCopy = z.infer<typeof SectionCopy>;

export const AudienceMessages = z.object({
  student: SectionCopy.optional(),
  family: SectionCopy.optional(),
  educator: SectionCopy.optional(),
});
export type AudienceMessages = z.infer<typeof AudienceMessages>;

export const InputsUsed = z.object({
  profile: z.boolean().optional(),
  intake: z.boolean().optional(),
  student_voice_keys: z.array(z.string()).max(40).optional(),
  iep_doc_ids: z.array(z.string().uuid()).max(20).optional(),
  iep_extraction_ids: z.array(z.string().uuid()).max(20).optional(),
  goal_ids: z.array(z.string().uuid()).max(40).optional(),
  readiness_at: z.string().optional(),
  readiness_category_count: z.number().int().nonnegative().optional(),
  action_item_ids: z.array(z.string().uuid()).max(60).optional(),
  meeting_prep_ids: z.array(z.string().uuid()).max(20).optional(),
  saved_resource_ids: z.array(z.string().uuid()).max(60).optional(),
  partner_match_ids: z.array(z.string().uuid()).max(40).optional(),
  family_priorities_count: z.number().int().nonnegative().optional(),
  generated_at: z.string().optional(),
});
export type InputsUsed = z.infer<typeof InputsUsed>;

/** v2 additive block grafted onto PathwayReport via JSON merge. */
export const PathwayReportV2 = z.object({
  schema_version: z.literal(2),
  iep_plan_summary: IepPlanSummary.optional(),
  postsecondary_education_recs: z.array(PillarRec).max(8).optional(),
  employment_pathway_recs: z.array(PillarRec).max(8).optional(),
  independent_living_recs: z.array(PillarRec).max(8).optional(),
  community_participation_recs: z.array(PillarRec).max(8).optional(),
  resource_matches: z.array(ResourceMatch).max(20).optional(),
  partner_matches: z.array(PartnerMatch).max(20).optional(),
  missing_information_v2: z.array(MissingInfo).max(20).optional(),
  student_action_plan: ActionPlan.optional(),
  family_action_plan_v2: ActionPlan.optional(),
  educator_action_plan_v2: ActionPlan.optional(),
  cross_cutting_horizons: Horizons.optional(),
  meeting_prep_questions: z
    .array(
      z.object({
        question: z.string().trim().min(1).max(400),
        for_audience: z.enum(["student", "family", "educator", "team"]),
        why: z.string().trim().max(400).optional(),
      }),
    )
    .max(20)
    .optional(),
  audience_messages: AudienceMessages.optional(),
  inputs_used: InputsUsed.optional(),
});
export type PathwayReportV2 = z.infer<typeof PathwayReportV2>;

/* ---------- helpers ---------- */

export function isV2(content: unknown): content is { schema_version: 2 } & Record<string, unknown> {
  return (
    typeof content === "object" &&
    content !== null &&
    (content as { schema_version?: unknown }).schema_version === 2
  );
}

/**
 * Deterministic missing-information items computed from the input manifest.
 * Always merged into the AI-suggested list so we never silently drop a known gap.
 */
export function computeDeterministicGaps(inputs: InputsUsed): MissingInfo[] {
  const gaps: MissingInfo[] = [];
  if (!inputs.iep_doc_ids?.length) {
    gaps.push({
      topic: "Current IEP is not on file",
      why_it_matters:
        "Without the IEP, transition goals, accommodations, and services can't be verified or summarized accurately.",
      how_to_collect:
        "Upload the most recent IEP from the student profile's Documents tab.",
      owner_role: "case_manager",
      blocks_section: "iep_plan_summary",
    });
  }
  if (!inputs.student_voice_keys?.length) {
    gaps.push({
      topic: "Student voice responses haven't been captured yet",
      why_it_matters:
        "The Pathway Report leads with the student's own words. Without them, the plan reflects adults' assumptions rather than what the student actually wants.",
      how_to_collect:
        "Ask the student to answer the Student Voice prompts in their dashboard, or sit with them for 10 minutes during a check-in.",
      owner_role: "student",
      blocks_section: "student_voice",
    });
  }
  if (!inputs.readiness_category_count || inputs.readiness_category_count < 4) {
    gaps.push({
      topic: "Transition readiness has limited coverage",
      why_it_matters:
        "The Readiness Scorecard guides which pathway recommendations are realistic right now versus stretch goals.",
      how_to_collect:
        "Have the team rate self-advocacy, career awareness, job readiness, independent living, and at least one other domain.",
      owner_role: "case_manager",
      blocks_section: "readiness_scorecard",
    });
  }
  if (!inputs.goal_ids?.length) {
    gaps.push({
      topic: "No transition goals are recorded in the student profile",
      why_it_matters:
        "Goals anchor the recommendations to a measurable plan the team can monitor.",
      how_to_collect:
        "Add 2–4 transition goals on the student profile, even draft language. They can be refined at the next PPT.",
      owner_role: "case_manager",
      blocks_section: "current_transition_goals",
    });
  }
  if (!inputs.saved_resource_ids?.length) {
    gaps.push({
      topic: "No resources saved for this student yet",
      why_it_matters:
        "Resource matches feel real when the family has bookmarked things they've explored.",
      how_to_collect:
        "Browse the Resources tab and save items that match the student's interests.",
      owner_role: "family",
      blocks_section: "resource_matches",
    });
  }
  if (!inputs.partner_match_ids?.length) {
    gaps.push({
      topic: "No partner / opportunity matches accepted yet",
      why_it_matters:
        "Partner matches connect the plan to real programs, internships, and adult-service providers in the community.",
      how_to_collect:
        "Review the Partner Suggestions panel and accept matches that look like a good fit.",
      owner_role: "family",
      blocks_section: "partner_matches",
    });
  }
  return gaps;
}

/**
 * Generate a one-line change summary from a previous → next input manifest diff.
 */
export function diffInputsForChangeSummary(
  prev: InputsUsed | undefined,
  next: InputsUsed,
): string {
  if (!prev) return "Regenerated with the full Pathway Report (v2) format.";
  const parts: string[] = [];
  const addedDocs =
    (next.iep_doc_ids?.length ?? 0) - (prev.iep_doc_ids?.length ?? 0);
  if (addedDocs > 0) parts.push(`${addedDocs} new IEP doc${addedDocs === 1 ? "" : "s"}`);
  const newVoice =
    (next.student_voice_keys?.length ?? 0) - (prev.student_voice_keys?.length ?? 0);
  if (newVoice > 0) parts.push(`${newVoice} new Student Voice response${newVoice === 1 ? "" : "s"}`);
  const newReadiness =
    (next.readiness_category_count ?? 0) - (prev.readiness_category_count ?? 0);
  if (newReadiness > 0) parts.push(`${newReadiness} new readiness score${newReadiness === 1 ? "" : "s"}`);
  const newGoals = (next.goal_ids?.length ?? 0) - (prev.goal_ids?.length ?? 0);
  if (newGoals > 0) parts.push(`${newGoals} new goal${newGoals === 1 ? "" : "s"}`);
  const newSaved =
    (next.saved_resource_ids?.length ?? 0) - (prev.saved_resource_ids?.length ?? 0);
  if (newSaved > 0) parts.push(`${newSaved} new saved resource${newSaved === 1 ? "" : "s"}`);
  const newPartner =
    (next.partner_match_ids?.length ?? 0) - (prev.partner_match_ids?.length ?? 0);
  if (newPartner > 0) parts.push(`${newPartner} new partner match${newPartner === 1 ? "" : "es"}`);
  if (parts.length === 0) return "Regenerated; no new inputs detected.";
  return `Regenerated — ${parts.join(", ")}.`;
}
