// Comprehensive curated resource library for TransitionForward.
// Pure data — no runtime side effects. Used by /resources.

export type ResourceFormat =
  | "article"
  | "video"
  | "podcast"
  | "book"
  | "checklist"
  | "assessment"
  | "worksheet"
  | "guide"
  | "tool"
  | "agency";

export type ResourceAudience =
  | "student"
  | "family"
  | "teacher"
  | "admin"
  | "school_admin"
  | "district_admin"
  | "partner";


export type ResourceTopic =
  | "transition-planning"
  | "iep-ppt"
  | "self-advocacy"
  | "career"
  | "employment"
  | "postsecondary"
  | "independent-living"
  | "family-support"
  | "teacher-tools"
  | "ct-resources";

export type ResourceGrade =
  | "middle"
  | "9"
  | "10"
  | "11"
  | "12"
  | "18-22";

export type ReadingLevel = "student" | "family" | "professional";
export type LocationScope = "national" | "connecticut" | "local";
export type TimeNeeded = "quick" | "deep" | "workshop" | "printable";

export type Resource = {
  id: string;
  title: string;
  description: string;
  whyItHelps?: string;
  format: ResourceFormat;
  audiences: ResourceAudience[];
  topics: ResourceTopic[];
  grades?: ResourceGrade[];
  readingLevel?: ReadingLevel;
  location: LocationScope;
  time: TimeNeeded;
  estimatedTime: string; // human label
  source: string;
  author?: string;
  link?: string;
  youtubeId?: string;
  audioUrl?: string;
  podcastTitle?: string;
  episodeTitle?: string;
  featured?: boolean;
};

export const TOPIC_META: Record<ResourceTopic, { label: string; description: string }> = {
  "transition-planning": {
    label: "Transition Planning Basics",
    description:
      "What transition planning is, when it starts, why it matters, and how families and students participate.",
  },
  "iep-ppt": {
    label: "IEP & PPT Meeting Support",
    description:
      "Understanding transition sections of the IEP, preparing for meetings, and decoding special education language.",
  },
  "self-advocacy": {
    label: "Student Self-Advocacy",
    description:
      "Tools that help students understand their strengths, ask for help, and lead their own meetings.",
  },
  career: {
    label: "Career Exploration",
    description:
      "Interest inventories, career clusters, industry tours, and pathways into trades, healthcare, tech and the arts.",
  },
  employment: {
    label: "Employment Readiness",
    description:
      "Resumes, interviews, workplace behavior, first-job prep, and supported employment.",
  },
  postsecondary: {
    label: "Postsecondary Education & Training",
    description:
      "College, technical schools, certificates, apprenticeships, disability services, and financial aid.",
  },
  "independent-living": {
    label: "Independent Living Skills",
    description:
      "Daily routines, money, transportation, cooking, health, housing, safety, and executive functioning.",
  },
  "family-support": {
    label: "Family & Parent Support",
    description:
      "Helping families support independence, decision-making, guardianship, and connection to agencies.",
  },
  "teacher-tools": {
    label: "Teacher & Case Manager Tools",
    description:
      "Transition assessments, goal writing, progress monitoring, lesson ideas, and documentation.",
  },
  "ct-resources": {
    label: "Connecticut-Specific Resources",
    description:
      "Connecticut agencies, programs, and supports — from BRS and DDS to Level Up and 211.",
  },
};

export const FORMAT_META: Record<ResourceFormat, { label: string; verb: string }> = {
  article: { label: "Article", verb: "Read article" },
  video: { label: "Video", verb: "Watch" },
  podcast: { label: "Podcast", verb: "Listen" },
  book: { label: "Book", verb: "Read more" },
  checklist: { label: "Checklist", verb: "Open checklist" },
  assessment: { label: "Assessment", verb: "Take assessment" },
  worksheet: { label: "Worksheet", verb: "Download worksheet" },
  guide: { label: "Guide", verb: "Open guide" },
  tool: { label: "Online Tool", verb: "Launch tool" },
  agency: { label: "Agency", verb: "Visit agency" },
};

export const AUDIENCE_META: Record<ResourceAudience, string> = {
  student: "Student",
  family: "Parent / Guardian",
  teacher: "Educator / Case Manager",
  admin: "School Administrator",
  school_admin: "School Administrator",
  district_admin: "School District Administrator",
  partner: "Partner Organization",
};


export const RESOURCES: Resource[] = [
  // ───────────────────────── Transition Planning Basics
  {
    id: "tp-1",
    title: "What Is Transition Planning, Really?",
    description: "A short, calm explainer for families hearing 'transition plan' for the first time.",
    format: "video",
    audiences: ["family", "student"],
    topics: ["transition-planning"],
    grades: ["middle", "9", "10"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "6 min watch",
    source: "PACER National Parent Center",
    youtubeId: "kCS8RJ4ZdaA",
    featured: true,
  },
  {
    id: "tp-2",
    title: "The Transition Timeline: Age 14 to 22",
    description: "A grade-by-grade map of what should happen, when, and who is responsible.",
    format: "guide",
    audiences: ["family", "teacher"],
    topics: ["transition-planning"],
    grades: ["middle", "9", "10", "11", "12"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "15 min read",
    source: "National Technical Assistance Center on Transition",
    link: "https://transitionta.org/",
  },
  {
    id: "tp-3",
    title: "How Transition Connects to the IEP",
    description: "Where transition lives inside the IEP, and how postsecondary goals drive everything else.",
    format: "article",
    audiences: ["family", "teacher"],
    topics: ["transition-planning", "iep-ppt"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "8 min read",
    source: "Center for Parent Information & Resources",
    link: "https://www.parentcenterhub.org/transitionadult/",
  },
  {
    id: "tp-4",
    title: "Family Participation in Transition: A Conversation Guide",
    description: "Printable prompts to help families share hopes, worries, and routines before the next meeting.",
    format: "worksheet",
    audiences: ["family"],
    topics: ["transition-planning", "family-support"],
    readingLevel: "family",
    location: "national",
    time: "printable",
    estimatedTime: "Print & use",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── IEP & PPT Meeting Support
  {
    id: "iep-1",
    title: "Inside a Student-Led PPT Meeting",
    description: "Watch a real student lead her own planning meeting. The shift is quiet and total.",
    format: "video",
    audiences: ["student", "family", "teacher"],
    topics: ["iep-ppt", "self-advocacy"],
    grades: ["10", "11", "12"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "9 min watch",
    source: "CPIR Center",
    youtubeId: "3W6Ed4dxLDA",
    featured: true,
  },
  {
    id: "iep-2",
    title: "Questions Every Family Should Ask at the Transition PPT",
    description: "Twelve questions that turn a status update into a planning meeting.",
    format: "checklist",
    audiences: ["family"],
    topics: ["iep-ppt"],
    readingLevel: "family",
    location: "national",
    time: "printable",
    estimatedTime: "1 page",
    source: "TransitionForward Studio",
  },
  {
    id: "iep-3",
    title: "Plain-Language Special Education Glossary",
    description: "100+ acronyms and terms decoded — FAPE, LRE, PLAAFP, BRS, and more.",
    format: "guide",
    audiences: ["family", "student"],
    topics: ["iep-ppt"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "Reference",
    source: "Understood.org",
    link: "https://www.understood.org/",
  },
  {
    id: "iep-4",
    title: "Writing Postsecondary Goals That Actually Mean Something",
    description: "What separates a measurable postsecondary goal from a wish.",
    format: "video",
    audiences: ["teacher"],
    topics: ["iep-ppt", "teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "12 min watch",
    source: "IRIS Center, Vanderbilt",
    youtubeId: "1aA1WGON49E",
  },
  {
    id: "iep-5",
    title: "Meeting Prep Checklist for Students",
    description: "Six steps to help a student walk into the room ready, not nervous.",
    format: "checklist",
    audiences: ["student"],
    topics: ["iep-ppt", "self-advocacy"],
    grades: ["10", "11", "12"],
    readingLevel: "student",
    location: "national",
    time: "printable",
    estimatedTime: "1 page",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── Student Self-Advocacy
  {
    id: "sa-1",
    title: "Knowing Yourself: Strengths, Needs, and What You Want",
    description: "A self-reflection worksheet students can fill out alone or with a trusted adult.",
    format: "worksheet",
    audiences: ["student"],
    topics: ["self-advocacy"],
    grades: ["9", "10", "11", "12"],
    readingLevel: "student",
    location: "national",
    time: "printable",
    estimatedTime: "20 min",
    source: "TransitionForward Studio",
  },
  {
    id: "sa-2",
    title: "How to Ask for Help (Without Feeling Weird About It)",
    description: "Scripts and sentence starters for class, work, and life.",
    format: "article",
    audiences: ["student"],
    topics: ["self-advocacy"],
    grades: ["middle", "9", "10", "11", "12"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "5 min read",
    source: "Think College",
    link: "https://thinkcollege.net/",
  },
  {
    id: "sa-3",
    title: "Disability Disclosure: Your Choice, Your Words",
    description: "When and how to talk about your disability at school, work, or college.",
    format: "guide",
    audiences: ["student"],
    topics: ["self-advocacy", "employment", "postsecondary"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "deep",
    estimatedTime: "10 min read",
    source: "Office of Disability Employment Policy",
    link: "https://www.dol.gov/agencies/odep/program-areas/individuals/youth/transition",
  },
  {
    id: "sa-4",
    title: "Self-Advocacy Questionnaire",
    description: "Twenty quick questions that show students where they are confident and where to build skill.",
    format: "assessment",
    audiences: ["student", "teacher"],
    topics: ["self-advocacy"],
    grades: ["9", "10", "11", "12"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "10 min",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── Career Exploration
  {
    id: "ce-1",
    title: "O*NET Interest Profiler",
    description: "Free 60-question inventory that suggests careers matching your interests.",
    format: "tool",
    audiences: ["student"],
    topics: ["career"],
    grades: ["9", "10", "11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "deep",
    estimatedTime: "20 min",
    source: "U.S. Department of Labor",
    link: "https://www.mynextmove.org/explore/ip",
    featured: true,
  },
  {
    id: "ce-2",
    title: "The 16 Career Clusters Explained",
    description: "A friendly overview of every major career family, from agriculture to IT.",
    format: "guide",
    audiences: ["student", "family", "teacher"],
    topics: ["career"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "10 min read",
    source: "Advance CTE",
    link: "https://careertech.org/career-clusters/",
  },
  {
    id: "ce-3",
    title: "Job Shadow Planning Worksheet",
    description: "Plan a job shadow, capture what you saw, and decide what to try next.",
    format: "worksheet",
    audiences: ["student", "teacher"],
    topics: ["career", "employment"],
    grades: ["10", "11", "12"],
    readingLevel: "student",
    location: "national",
    time: "printable",
    estimatedTime: "2 pages",
    source: "TransitionForward Studio",
  },
  {
    id: "ce-4",
    title: "Careers in the Trades: A Visual Tour",
    description: "Plumbing, electrical, HVAC, welding — what the day actually looks like.",
    format: "video",
    audiences: ["student", "family"],
    topics: ["career"],
    grades: ["10", "11", "12"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "8 min watch",
    source: "Mike Rowe Works",
    youtubeId: "DvPbnGfDhRk",
  },
  {
    id: "ce-5",
    title: "Healthcare Career Pathways",
    description: "From medical assistant to nursing aide — entry points that don't require four years.",
    format: "article",
    audiences: ["student", "family"],
    topics: ["career"],
    grades: ["11", "12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "7 min read",
    source: "Bureau of Labor Statistics",
    link: "https://www.bls.gov/ooh/healthcare/",
  },
  {
    id: "ce-6",
    title: "Entrepreneurship for Young People with Disabilities",
    description: "Real stories of self-employment as a postsecondary outcome.",
    format: "article",
    audiences: ["student", "family", "teacher"],
    topics: ["career", "employment"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "12 min read",
    source: "Griffin-Hammis Associates",
    link: "https://www.griffinhammis.com/",
  },

  // ───────────────────────── Employment Readiness
  {
    id: "er-1",
    title: "First Resume Builder",
    description: "Free guided builder designed for students with little or no work history.",
    format: "tool",
    audiences: ["student"],
    topics: ["employment"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "deep",
    estimatedTime: "30 min",
    source: "Indeed Career Guide",
    link: "https://www.indeed.com/career-advice/resumes-cover-letters",
  },
  {
    id: "er-2",
    title: "Interview Practice: 20 Common Questions",
    description: "Practice answers, sample responses, and tips for what to do with your hands.",
    format: "worksheet",
    audiences: ["student"],
    topics: ["employment"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "printable",
    estimatedTime: "20 min",
    source: "TransitionForward Studio",
  },
  {
    id: "er-3",
    title: "Workplace Soft Skills: A Visual Guide",
    description: "Showing up, communicating, asking questions, and bouncing back.",
    format: "video",
    audiences: ["student"],
    topics: ["employment"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "7 min watch",
    source: "Project SEARCH",
    youtubeId: "QXfWVO6f3Ek",
  },
  {
    id: "er-4",
    title: "Workplace Accommodations Toolkit",
    description: "How to request accommodations on the job — examples, sample letters, your rights.",
    format: "guide",
    audiences: ["student", "family", "teacher"],
    topics: ["employment", "self-advocacy"],
    grades: ["12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "15 min read",
    source: "Job Accommodation Network (JAN)",
    link: "https://askjan.org/",
  },
  {
    id: "er-5",
    title: "Work-Based Learning Planning Form",
    description: "For teachers and case managers planning internships and community work.",
    format: "worksheet",
    audiences: ["teacher"],
    topics: ["employment", "teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "printable",
    estimatedTime: "2 pages",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── Postsecondary
  {
    id: "ps-1",
    title: "Think College: Inclusive Postsecondary Programs",
    description: "Searchable directory of college programs for students with intellectual disability.",
    format: "tool",
    audiences: ["student", "family", "teacher"],
    topics: ["postsecondary"],
    grades: ["11", "12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "20 min",
    source: "Think College",
    link: "https://thinkcollege.net/college-search",
    featured: true,
  },
  {
    id: "ps-2",
    title: "How College Disability Services Actually Work",
    description: "The difference between IDEA and ADA, and what to do in the first month on campus.",
    format: "video",
    audiences: ["student", "family"],
    topics: ["postsecondary"],
    grades: ["11", "12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "10 min watch",
    source: "AHEAD",
    youtubeId: "8mglDLDi5xQ",
  },
  {
    id: "ps-3",
    title: "FAFSA Walkthrough for Families",
    description: "Plain-language steps for completing the FAFSA, with screenshots.",
    format: "guide",
    audiences: ["family", "student"],
    topics: ["postsecondary"],
    grades: ["12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "30 min",
    source: "Federal Student Aid",
    link: "https://studentaid.gov/h/apply-for-aid/fafsa",
  },
  {
    id: "ps-4",
    title: "Apprenticeships: Earn While You Learn",
    description: "Registered apprenticeships in trades, tech, and healthcare — what they pay and how to start.",
    format: "article",
    audiences: ["student", "family"],
    topics: ["postsecondary", "career"],
    grades: ["11", "12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "8 min read",
    source: "Apprenticeship.gov",
    link: "https://www.apprenticeship.gov/",
  },
  {
    id: "ps-5",
    title: "Campus Readiness Checklist",
    description: "A summer-before-college packing list that goes beyond bed sheets.",
    format: "checklist",
    audiences: ["student", "family"],
    topics: ["postsecondary", "independent-living"],
    grades: ["12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "printable",
    estimatedTime: "2 pages",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── Independent Living
  {
    id: "il-1",
    title: "Casey Life Skills Assessment",
    description: "Free assessment covering money, daily living, work, education, and relationships.",
    format: "assessment",
    audiences: ["student", "family", "teacher"],
    topics: ["independent-living"],
    grades: ["10", "11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "deep",
    estimatedTime: "45 min",
    source: "Casey Family Programs",
    link: "https://caseylifeskills.secure.force.com/",
    featured: true,
  },
  {
    id: "il-2",
    title: "Monthly Budget Worksheet for First-Time Earners",
    description: "Simple, visual budget for students starting a first job.",
    format: "worksheet",
    audiences: ["student"],
    topics: ["independent-living"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "printable",
    estimatedTime: "1 page",
    source: "TransitionForward Studio",
  },
  {
    id: "il-3",
    title: "Cooking 10 Meals With a Microwave",
    description: "Real recipes for dorms, apartments, and group homes — no oven required.",
    format: "video",
    audiences: ["student"],
    topics: ["independent-living"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "12 min watch",
    source: "Tasty",
    youtubeId: "Z1V9b3p0Rqk",
  },
  {
    id: "il-4",
    title: "Public Transportation Practice Plan",
    description: "How to learn a bus route safely — solo trip in five sessions.",
    format: "guide",
    audiences: ["student", "family", "teacher"],
    topics: ["independent-living"],
    grades: ["10", "11", "12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "15 min read",
    source: "Easterseals",
    link: "https://www.easterseals.com/",
  },
  {
    id: "il-5",
    title: "Executive Functioning Strategies that Stick",
    description: "Calendars, timers, body-doubling, and the case against motivation.",
    format: "article",
    audiences: ["student", "family", "teacher"],
    topics: ["independent-living"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "8 min read",
    source: "Smart Kids with Learning Disabilities",
    link: "https://www.smartkidswithld.org/",
  },

  // ───────────────────────── Family & Parent Support
  {
    id: "fs-1",
    title: "Age of Majority, in Plain English",
    description: "What changes the day your student turns 18, and what you can decide together long before.",
    format: "podcast",
    audiences: ["family"],
    topics: ["family-support"],
    grades: ["11", "12"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "19 min listen",
    source: "TransitionForward Studio",
    podcastTitle: "The Transition Years",
    episodeTitle: "Age of Majority, in Plain English",
    audioUrl: "https://cdn.simplecast.com/audio/sample.mp3",
  },
  {
    id: "fs-2",
    title: "Supported Decision-Making vs. Guardianship",
    description: "A side-by-side comparison and a values worksheet to use as a family.",
    format: "guide",
    audiences: ["family"],
    topics: ["family-support"],
    grades: ["11", "12", "18-22"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "20 min read",
    source: "Center for Public Representation",
    link: "https://supporteddecisions.org/",
  },
  {
    id: "fs-3",
    title: "Letting Go on Purpose: A Parent Conversation",
    description: "Two parents share what changed when they stopped doing it for them.",
    format: "podcast",
    audiences: ["family"],
    topics: ["family-support"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "28 min listen",
    source: "TransitionForward Studio",
    podcastTitle: "The Transition Years",
    episodeTitle: "Letting Go on Purpose",
    audioUrl: "https://cdn.simplecast.com/audio/sample.mp3",
  },
  {
    id: "fs-4",
    title: "Family-School Partnership Toolkit",
    description: "Ways to build a relationship with the team that lasts longer than one school year.",
    format: "guide",
    audiences: ["family", "teacher"],
    topics: ["family-support", "teacher-tools"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "15 min read",
    source: "Harvard Family Research Project",
    link: "https://archive.globalfrp.org/family-involvement",
  },

  // ───────────────────────── Teacher & Case Manager
  {
    id: "tt-1",
    title: "Transition Assessment Library",
    description: "Free formal and informal transition assessments organized by domain.",
    format: "tool",
    audiences: ["teacher"],
    topics: ["teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "Reference",
    source: "Zarrow Center, University of Oklahoma",
    link: "https://www.ou.edu/education/centers-and-partnerships/zarrow",
  },
  {
    id: "tt-2",
    title: "Student Interview Protocol",
    description: "A structured conversation guide for getting beyond yes-and-no answers.",
    format: "worksheet",
    audiences: ["teacher"],
    topics: ["teacher-tools", "self-advocacy"],
    readingLevel: "professional",
    location: "national",
    time: "printable",
    estimatedTime: "3 pages",
    source: "TransitionForward Studio",
  },
  {
    id: "tt-3",
    title: "Writing IEP Goals Linked to Transition Outcomes",
    description: "A model and rubric for goals that genuinely move postsecondary outcomes.",
    format: "article",
    audiences: ["teacher"],
    topics: ["teacher-tools", "iep-ppt"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "12 min read",
    source: "NTACT",
    link: "https://transitionta.org/",
  },
  {
    id: "tt-4",
    title: "Progress Monitoring Tracker",
    description: "Weekly check-in template that doubles as documentation for re-evals.",
    format: "worksheet",
    audiences: ["teacher"],
    topics: ["teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "printable",
    estimatedTime: "1 page",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── Connecticut-Specific
  {
    id: "ct-1",
    title: "Connecticut Secondary Transition Resources",
    description: "The official CSDE hub for secondary transition guidance, forms, and trainings.",
    format: "agency",
    audiences: ["family", "teacher", "school_admin"],
    topics: ["ct-resources", "transition-planning"],
    readingLevel: "professional",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "CT State Department of Education",
    link: "https://portal.ct.gov/sde/special-education/bureau-of-special-education/transition",
    featured: true,
  },
  {
    id: "ct-2",
    title: "Connecticut Parent Advocacy Center (CPAC)",
    description: "Free, family-led support for navigating special education. Trained parents on the phone before your next meeting.",
    format: "agency",
    audiences: ["family"],
    topics: ["ct-resources", "family-support"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "CPAC",
    link: "https://cpacinc.org/",
  },
  {
    id: "ct-3",
    title: "Bureau of Rehabilitation Services (BRS)",
    description: "Vocational rehabilitation for eligible students. Job coaching, training dollars, on-the-job supports. Door opens at 16.",
    format: "agency",
    audiences: ["family", "student", "teacher"],
    topics: ["ct-resources", "employment"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "CT Aging & Disability Services",
    link: "https://portal.ct.gov/aging-and-disability/content-pages/bureaus/bureau-of-rehabilitation-services",
  },
  {
    id: "ct-4",
    title: "Level Up CT",
    description: "Pre-employment transition services for CT students with disabilities, ages 14–21.",
    format: "agency",
    audiences: ["student", "family", "teacher"],
    topics: ["ct-resources", "employment", "career"],
    grades: ["9", "10", "11", "12", "18-22"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "BRS Level Up Program",
    link: "https://portal.ct.gov/aging-and-disability/content-pages/programs/level-up",
  },
  {
    id: "ct-5",
    title: "Department of Aging and Disability Services",
    description: "The umbrella agency for BRS, services for the blind, deaf, and older adults in Connecticut.",
    format: "agency",
    audiences: ["family", "student"],
    topics: ["ct-resources"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "State of Connecticut",
    link: "https://portal.ct.gov/aging-and-disability",
  },
  {
    id: "ct-6",
    title: "Department of Developmental Services (DDS)",
    description: "Adult services for individuals with intellectual disability and autism. Apply early — eligibility can take a year or more.",
    format: "agency",
    audiences: ["family"],
    topics: ["ct-resources", "family-support"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "State of Connecticut",
    link: "https://portal.ct.gov/dds",
  },
  {
    id: "ct-7",
    title: "211 Connecticut",
    description: "One number for housing, food, transportation, mental health, and crisis support statewide.",
    format: "agency",
    audiences: ["family", "student"],
    topics: ["ct-resources", "independent-living"],
    readingLevel: "family",
    location: "connecticut",
    time: "quick",
    estimatedTime: "Reference",
    source: "United Way of CT",
    link: "https://www.211ct.org/",
  },
  {
    id: "ct-8",
    title: "Connecticut Community Colleges (C State)",
    description: "All twelve campuses now unified — programs, disability services, and admissions in one place.",
    format: "agency",
    audiences: ["student", "family"],
    topics: ["ct-resources", "postsecondary"],
    grades: ["11", "12", "18-22"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "CT State Community College",
    link: "https://www.ctstate.edu/",
  },
  {
    id: "ct-9",
    title: "Connecticut Technical Education and Career System",
    description: "CT's 17 technical high schools — apply in 8th grade for trades, healthcare, automotive, culinary.",
    format: "agency",
    audiences: ["family", "student"],
    topics: ["ct-resources", "career", "postsecondary"],
    grades: ["middle"],
    readingLevel: "family",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "CT Technical Education",
    link: "https://www.cttech.org/",
  },
  {
    id: "ct-10",
    title: "Connecticut Workforce Development Boards",
    description: "Find your regional workforce board — youth programs, training dollars, and summer employment.",
    format: "agency",
    audiences: ["student", "family", "partner"],
    topics: ["ct-resources", "employment"],
    readingLevel: "family",
    location: "local",
    time: "deep",
    estimatedTime: "Reference",
    source: "CT Department of Labor",
    link: "https://www.ctdol.state.ct.us/workforce-development-boards.htm",
  },
  {
    id: "ct-11",
    title: "SERC — State Education Resource Center",
    description: "Workshops, family nights, and educator institutes on transition throughout the year.",
    format: "agency",
    audiences: ["teacher", "family", "school_admin"],
    topics: ["ct-resources", "teacher-tools"],
    readingLevel: "professional",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "Connecticut training arm",
    link: "https://ctserc.org/",
  },

  // ───────────────────────── Books
  {
    id: "bk-1",
    title: "The Self-Advocacy Strategy for Education and Transition Planning",
    description: "The original I-PLAN curriculum — teach students to drive their own meetings.",
    whyItHelps: "Step-by-step lessons educators can run as a six-week unit.",
    format: "book",
    audiences: ["teacher", "student"],
    topics: ["self-advocacy", "teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "workshop",
    estimatedTime: "Book",
    source: "Edge Enterprises",
    author: "Anthony Van Reusen et al.",
    link: "https://www.edgeenterprisesinc.com/",
  },
  {
    id: "bk-2",
    title: "Smart but Scattered Teens",
    description: "Executive functioning skills, framed for the teen who keeps losing the planner.",
    whyItHelps: "Practical scripts and routines families can use without a clinician.",
    format: "book",
    audiences: ["family", "student"],
    topics: ["independent-living", "family-support"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "Book",
    source: "Guilford Press",
    author: "Richard Guare, Peg Dawson, Colin Guare",
    link: "https://www.smartbutscatteredkids.com/",
  },
  {
    id: "bk-3",
    title: "Wrightslaw: From Emotions to Advocacy",
    description: "The classic plain-language playbook for navigating special education.",
    whyItHelps: "Helps families separate the law, the records, and the relationships.",
    format: "book",
    audiences: ["family"],
    topics: ["family-support", "iep-ppt"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "Book",
    source: "Harbor House Law Press",
    author: "Pam & Pete Wright",
    link: "https://www.wrightslaw.com/",
  },
  {
    id: "bk-4",
    title: "Life After High School: A Guide for Students with Disabilities",
    description: "A teen-friendly walkthrough of what comes after a diploma or certificate.",
    whyItHelps: "Written directly to the student, not over their head.",
    format: "book",
    audiences: ["student", "family"],
    topics: ["transition-planning", "postsecondary"],
    grades: ["11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "deep",
    estimatedTime: "Book",
    source: "Free Spirit Publishing",
    author: "Susan Yellin & Christina Cacioppo Bertsch",
    link: "https://www.freespirit.com/",
  },
  {
    id: "bk-5",
    title: "The Survival Guide for Kids with Autism Spectrum Disorders",
    description: "Strategies for friendships, school, and growing up — written for students themselves.",
    whyItHelps: "Validates experiences in language students relate to.",
    format: "book",
    audiences: ["student", "family"],
    topics: ["self-advocacy", "independent-living"],
    grades: ["middle", "9", "10"],
    readingLevel: "student",
    location: "national",
    time: "deep",
    estimatedTime: "Book",
    source: "Free Spirit Publishing",
    author: "Elizabeth Verdick & Elizabeth Reeve",
    link: "https://www.freespirit.com/",
  },
  {
    id: "bk-6",
    title: "Transition Planning for Secondary Students with Disabilities",
    description: "The textbook used in graduate programs — comprehensive professional reference.",
    whyItHelps: "Dense, but the definitive professional reference for case managers.",
    format: "book",
    audiences: ["teacher"],
    topics: ["teacher-tools", "transition-planning"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "Book",
    source: "Pearson",
    author: "Robert Flexer et al.",
  },

  // ───────────────────────── Podcasts (additional)
  {
    id: "pc-1",
    title: "Teach Me, Teacher: Special Ed Transitions",
    description: "Conversations with educators about real classroom transition practice.",
    format: "podcast",
    audiences: ["teacher"],
    topics: ["teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "quick",
    estimatedTime: "45 min listen",
    source: "Teach Me, Teacher Podcast",
    podcastTitle: "Teach Me, Teacher",
    episodeTitle: "Building Real Transition Plans",
    audioUrl: "https://cdn.simplecast.com/audio/sample.mp3",
  },
  {
    id: "pc-2",
    title: "Disability Visibility: Stories About Work",
    description: "First-person stories about employment with a disability.",
    format: "podcast",
    audiences: ["student", "family"],
    topics: ["employment", "self-advocacy"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "32 min listen",
    source: "Disability Visibility Project",
    podcastTitle: "Disability Visibility",
    episodeTitle: "What Work Looks Like",
    audioUrl: "https://cdn.simplecast.com/audio/sample.mp3",
  },
  {
    id: "pc-3",
    title: "ThinkInclusive: Transition to Adulthood",
    description: "Educators and self-advocates on what inclusion looks like after high school.",
    format: "podcast",
    audiences: ["teacher", "family"],
    topics: ["postsecondary", "family-support"],
    readingLevel: "family",
    location: "national",
    time: "quick",
    estimatedTime: "38 min listen",
    source: "MCIE / ThinkInclusive",
    podcastTitle: "ThinkInclusive",
    episodeTitle: "Beyond Graduation",
    audioUrl: "https://cdn.simplecast.com/audio/sample.mp3",
  },

  // ───────────────────────── Online Tools (additional)
  {
    id: "tl-1",
    title: "College Navigator",
    description: "Federal database — search any U.S. college by major, location, size, and cost.",
    format: "tool",
    audiences: ["student", "family"],
    topics: ["postsecondary"],
    grades: ["11", "12"],
    readingLevel: "family",
    location: "national",
    time: "deep",
    estimatedTime: "20 min",
    source: "National Center for Education Statistics",
    link: "https://nces.ed.gov/collegenavigator/",
  },
  {
    id: "tl-2",
    title: "Mango Money: Budgeting Game",
    description: "Interactive budget simulator built for teen and young adult learners.",
    format: "tool",
    audiences: ["student"],
    topics: ["independent-living"],
    grades: ["10", "11", "12", "18-22"],
    readingLevel: "student",
    location: "national",
    time: "quick",
    estimatedTime: "15 min",
    source: "Practical Money Skills",
    link: "https://www.practicalmoneyskills.com/en/play",
  },

  // ───────────────────────── Educator / Case Manager
  {
    id: "ecm-1",
    title: "Indicator 13 Checklist for Transition IEPs",
    description: "The federal compliance checklist case managers use to make sure every transition IEP holds up to audit.",
    format: "checklist",
    audiences: ["teacher"],
    topics: ["teacher-tools", "iep-ppt"],
    readingLevel: "professional",
    location: "national",
    time: "printable",
    estimatedTime: "2 pages",
    source: "National Technical Assistance Center on Transition",
    link: "https://transitionta.org/indicator13/",
  },
  {
    id: "ecm-2",
    title: "Age-Appropriate Transition Assessment Toolkit",
    description: "A vetted menu of free transition assessments mapped to age, ability, and post-school domain.",
    format: "guide",
    audiences: ["teacher"],
    topics: ["teacher-tools", "transition-planning"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "30 min",
    source: "NTACT:C",
    link: "https://transitionta.org/age-appropriate-transition-assessment-toolkit/",
  },
  {
    id: "ecm-3",
    title: "Caseload Sanity: A Weekly Cadence for Transition Case Managers",
    description: "A working rhythm for tracking goals, agency referrals, and PPT prep without losing your evenings.",
    format: "article",
    audiences: ["teacher"],
    topics: ["teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "quick",
    estimatedTime: "7 min read",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── School Administrator
  {
    id: "sa-admin-1",
    title: "Building a Transition Program That Actually Works",
    description: "What principals and special education directors put in place when student outcomes improve.",
    format: "guide",
    audiences: ["school_admin"],
    topics: ["teacher-tools", "transition-planning"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "20 min read",
    source: "CEEDAR Center",
    link: "https://ceedar.education.ufl.edu/",
  },
  {
    id: "sa-admin-2",
    title: "Post-School Outcomes Data: What to Watch as a School Leader",
    description: "The five metrics that signal whether your transition program is working — and how to read them.",
    format: "article",
    audiences: ["school_admin"],
    topics: ["teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "quick",
    estimatedTime: "8 min read",
    source: "NTACT:C",
    link: "https://transitionta.org/data/",
  },
  {
    id: "sa-admin-3",
    title: "Interagency Agreements: A Sample Template for Schools and Adult Agencies",
    description: "Editable language for school-to-agency MOUs covering BRS, DDS, and workforce partners.",
    format: "worksheet",
    audiences: ["school_admin", "district_admin"],
    topics: ["teacher-tools", "ct-resources"],
    readingLevel: "professional",
    location: "national",
    time: "printable",
    estimatedTime: "Reference",
    source: "TransitionForward Studio",
  },

  // ───────────────────────── District Administrator
  {
    id: "dist-1",
    title: "Designing District-Wide Transition Services",
    description: "How districts structure a coherent 14-to-22 continuum across multiple schools and programs.",
    format: "guide",
    audiences: ["district_admin"],
    topics: ["teacher-tools", "transition-planning"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "25 min read",
    source: "CCSSO / NASDSE",
    link: "https://www.nasdse.org/",
  },
  {
    id: "dist-2",
    title: "Indicator 14 Post-School Outcomes — Reading Your District Report",
    description: "How to interpret your state's Indicator 14 data and turn it into a district improvement plan.",
    format: "article",
    audiences: ["district_admin", "school_admin"],
    topics: ["teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "12 min read",
    source: "NTACT:C",
    link: "https://transitionta.org/indicator14/",
  },
  {
    id: "dist-3",
    title: "Connecticut Special Education Director Resources",
    description: "CSDE's hub for district-level special education leaders — guidance, fiscal, and compliance.",
    format: "agency",
    audiences: ["district_admin", "school_admin"],
    topics: ["ct-resources", "teacher-tools"],
    readingLevel: "professional",
    location: "connecticut",
    time: "deep",
    estimatedTime: "Reference",
    source: "CT State Department of Education",
    link: "https://portal.ct.gov/sde/special-education/bureau-of-special-education",
  },

  // ───────────────────────── Partner Organization
  {
    id: "part-1",
    title: "Becoming an Effective Employer Partner for Youth with Disabilities",
    description: "Practical guidance for businesses hosting internships, job shadows, and first hires.",
    format: "guide",
    audiences: ["partner"],
    topics: ["employment", "career"],
    readingLevel: "professional",
    location: "national",
    time: "deep",
    estimatedTime: "15 min read",
    source: "Partnership on Inclusive Apprenticeship",
    link: "https://inclusiveapprenticeship.org/",
  },
  {
    id: "part-2",
    title: "Community-Based Instruction Site Agreement",
    description: "A template community partners and schools can co-sign before hosting students on site.",
    format: "worksheet",
    audiences: ["partner", "teacher"],
    topics: ["employment", "teacher-tools"],
    readingLevel: "professional",
    location: "national",
    time: "printable",
    estimatedTime: "2 pages",
    source: "TransitionForward Studio",
  },
  {
    id: "part-3",
    title: "How Workforce Boards and Schools Build Pipelines Together",
    description: "Models of CT workforce boards partnering with high schools to fund summer youth employment.",
    format: "article",
    audiences: ["partner", "school_admin", "district_admin"],
    topics: ["ct-resources", "employment"],
    readingLevel: "professional",
    location: "connecticut",
    time: "quick",
    estimatedTime: "8 min read",
    source: "CT Department of Labor",
    link: "https://www.ctdol.state.ct.us/workforce-development-boards.htm",
  },
];


export const RECOMMENDATION_RULES: Array<{
  trigger: string;
  match: (text: string) => boolean;
  topics: ResourceTopic[];
  label: string;
}> = [
  {
    trigger: "employment",
    match: (t) => /(job|work|employ|career|intern)/i.test(t),
    topics: ["employment", "career"],
    label: "Career & employment goals",
  },
  {
    trigger: "college",
    match: (t) => /(college|university|postsecondary|degree)/i.test(t),
    topics: ["postsecondary"],
    label: "Postsecondary education plans",
  },
  {
    trigger: "independent",
    match: (t) => /(independent|living|cook|budget|transport|money)/i.test(t),
    topics: ["independent-living"],
    label: "Independent living goals",
  },
  {
    trigger: "advocacy",
    match: (t) => /(advocate|self|voice|speak|disclos)/i.test(t),
    topics: ["self-advocacy"],
    label: "Self-advocacy growth",
  },
];
