import { useEffect, useMemo, useState } from "react";
import { Copy, Printer, Users, GraduationCap, Check } from "lucide-react";
import type { PathwayReport } from "@/lib/pathway.functions";
import type { SupportedLanguage } from "@/lib/ai-assist.functions";
import { Button } from "@/components/ui/button";
import { AiAssistPanel } from "@/components/pathway/AiAssistPanel";
import { cn } from "@/lib/utils";

type Audience = "family" | "educator";


export function ReportView({
  name,
  report,
  onReset,
  resetLabel = "Create another report",
  initialAudience,
}: {
  name: string;
  report: PathwayReport;
  onReset?: () => void;
  resetLabel?: string;
  initialAudience?: Audience;
}) {
  const [audience, setAudience] = useState<Audience>(initialAudience ?? "family");
  const [copied, setCopied] = useState(false);
  const [displayReport, setDisplayReport] = useState<PathwayReport>(report);
  const [translatedTo, setTranslatedTo] = useState<SupportedLanguage | null>(null);

  // Sync ?view= in the URL so links are shareable per audience.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const v = params.get("view");
    if (v === "family" || v === "educator") setAudience(v);
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const url = new URL(window.location.href);
    url.searchParams.set("view", audience);
    window.history.replaceState({}, "", url.toString());
  }, [audience]);

  const heading = useMemo(
    () =>
      audience === "family"
        ? `A plan for ${name}.`
        : `PPT prep packet — ${name}`,
    [audience, name],
  );

  const subheading =
    audience === "family"
      ? displayReport.summary
      : "A teacher-facing snapshot to bring to the next Planning & Placement Team meeting. Use the talking points and next steps to keep the conversation focused on the student.";

  const copyLink = async () => {
    if (typeof window === "undefined") return;
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* ignore */
    }
  };

  return (
    <section className="report-root mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
      {/* Toolbar — hidden on print */}
      <div className="no-print mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-2 shadow-soft">
        <div
          role="tablist"
          aria-label="Choose a report view"
          className="inline-flex rounded-xl bg-muted p-1"
        >
          <AudienceTab
            active={audience === "family"}
            onClick={() => setAudience("family")}
            icon={<Users className="h-4 w-4" />}
            label="Family view"
            hint="Plain language"
          />
          <AudienceTab
            active={audience === "educator"}
            onClick={() => setAudience("educator")}
            icon={<GraduationCap className="h-4 w-4" />}
            label="Educator view"
            hint="PPT prep"
          />
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" size="sm" onClick={copyLink} aria-label="Copy shareable link">
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? "Link copied" : "Copy link"}
          </Button>
          <Button size="sm" onClick={() => window.print()}>
            <Printer className="h-4 w-4" /> Print / save as PDF
          </Button>
        </div>
      </div>

      {/* Header card */}
      <div
        className={cn(
          "rounded-3xl p-8 shadow-soft sm:p-10",
          audience === "family" ? "bg-gradient-hero" : "border bg-card",
        )}
      >
        <p className="text-xs font-semibold uppercase tracking-wider text-primary">
          {audience === "family" ? "Pathway Report" : "Educator PPT Prep"}
        </p>
        <h1 className="mt-2 font-display text-4xl font-medium tracking-tight sm:text-5xl">
          {heading}
        </h1>
        <p className="mt-4 text-base leading-relaxed text-foreground/80">{subheading}</p>
        <div className="mt-4 hidden text-xs text-muted-foreground print:block">
          Generated by TransitionForward · {new Date().toLocaleDateString()}
        </div>
      </div>

      {audience === "family" ? (
        <FamilyView name={name} report={displayReport} />
      ) : (
        <EducatorView name={name} report={displayReport} />
      )}

      <AiAssistPanel
        studentName={name}
        report={report}
        translatedTo={translatedTo}
        onTranslated={(next, lang) => {
          setDisplayReport(next);
          setTranslatedTo(lang);
        }}
        onReset={() => {
          setDisplayReport(report);
          setTranslatedTo(null);
        }}
      />


      <div className="no-print mt-10 flex flex-wrap gap-3">
        {onReset && (
          <Button onClick={onReset} variant="outline">
            {resetLabel}
          </Button>
        )}
        <Button onClick={() => window.print()}>
          <Printer className="h-4 w-4" /> Print / save as PDF
        </Button>
      </div>

      {/* Print styles: clean, page-friendly output. */}
      <style>{`
        @media print {
          @page { margin: 0.6in; }
          .no-print { display: none !important; }
          .report-root { padding: 0 !important; max-width: 100% !important; }
          .report-root .shadow-soft,
          .report-root .shadow-lift { box-shadow: none !important; }
          .report-root .rounded-3xl,
          .report-root .rounded-2xl { border-radius: 8px !important; }
          .report-root .bg-gradient-hero { background: #f6f8fb !important; }
          .report-root section,
          .report-root .page-break { break-inside: avoid; }
          .report-root h1, .report-root h2, .report-root h3 { color: #111 !important; }
          .report-root .text-muted-foreground { color: #444 !important; }
          .report-root a { color: inherit; text-decoration: none; }
        }
      `}</style>
    </section>
  );
}

function AudienceTab({
  active,
  onClick,
  icon,
  label,
  hint,
}: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
  hint: string;
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      className={cn(
        "flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
        active
          ? "bg-background text-foreground shadow-sm"
          : "text-muted-foreground hover:text-foreground",
      )}
    >
      {icon}
      <span>{label}</span>
      <span className="hidden text-xs font-normal text-muted-foreground sm:inline">· {hint}</span>
    </button>
  );
}

function FamilyView({ name, report }: { name: string; report: PathwayReport }) {
  return (
    <>
      <Block title="Strengths to lead with">
        <BulletList items={report.strengths_snapshot} />
      </Block>

      <Block title="Career pathways to explore">
        <div className="grid gap-4">
          {report.career_pathways.map((p) => (
            <div key={p.title} className="rounded-2xl border border-border/60 bg-card p-5">
              <h3 className="font-display text-xl font-medium">{p.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{p.why_it_fits}</p>
              <p className="mt-3 text-xs font-semibold uppercase tracking-wider text-primary">
                Example roles
              </p>
              <BulletList items={p.example_roles} />
              <p className="mt-3 text-xs font-semibold uppercase tracking-wider text-primary">
                First steps
              </p>
              <BulletList items={p.first_steps} />
            </div>
          ))}
        </div>
      </Block>

      <Block title="Education & training options">
        <BulletList items={report.education_training_options} />
      </Block>
      <Block title="Life skills to focus on">
        <BulletList items={report.life_skills_focus} />
      </Block>
      <Block title="Questions to bring to the next PPT">
        <BulletList items={report.family_questions_for_ppt} />
      </Block>

      <Block title="A gentle 30-day plan">
        <ol className="space-y-3">
          {report.thirty_day_plan.map((w) => (
            <li key={w.week} className="rounded-2xl border border-border/60 bg-card p-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-primary">
                Week {w.week}
              </p>
              <p className="mt-1 text-sm text-foreground">{w.action}</p>
            </li>
          ))}
        </ol>
      </Block>

      <div className="mt-10 rounded-3xl border border-border/60 bg-card p-6 shadow-soft">
        <p className="text-xs font-semibold uppercase tracking-wider text-primary">For {name}</p>
        <p className="mt-3 font-display text-xl italic text-foreground/90">
          {report.encouragement_to_student}
        </p>
      </div>
    </>
  );
}

function EducatorView({ name, report }: { name: string; report: PathwayReport }) {
  return (
    <>
      <Block title="At-a-glance">
        <div className="grid gap-3 sm:grid-cols-2">
          <Card title="Student strengths">
            <BulletList items={report.strengths_snapshot} compact />
          </Card>
          <Card title="Priority life-skill focus">
            <BulletList items={report.life_skills_focus} compact />
          </Card>
        </div>
      </Block>

      <Block title="Teacher next steps">
        <Card>
          <BulletList items={report.teacher_next_steps} />
        </Card>
      </Block>

      <Block title="Career pathway talking points">
        <div className="grid gap-3">
          {report.career_pathways.map((p) => (
            <div key={p.title} className="rounded-2xl border border-border/60 bg-card p-5">
              <div className="flex items-baseline justify-between gap-3">
                <h3 className="font-display text-lg font-medium">{p.title}</h3>
                <span className="text-xs uppercase tracking-wider text-muted-foreground">
                  pathway
                </span>
              </div>
              <p className="mt-2 text-sm text-muted-foreground">{p.why_it_fits}</p>
              <div className="mt-3 grid gap-3 sm:grid-cols-2">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-primary">
                    Roles to mention
                  </p>
                  <BulletList items={p.example_roles} compact />
                </div>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wider text-primary">
                    Concrete first steps
                  </p>
                  <BulletList items={p.first_steps} compact />
                </div>
              </div>
            </div>
          ))}
        </div>
      </Block>

      <Block title="Education & training routes to discuss">
        <Card>
          <BulletList items={report.education_training_options} />
        </Card>
      </Block>

      <Block title="Questions the family will likely raise">
        <Card>
          <BulletList items={report.family_questions_for_ppt} />
        </Card>
      </Block>

      <Block title="Proposed 30-day teaching plan">
        <ol className="grid gap-3 sm:grid-cols-2">
          {report.thirty_day_plan.map((w) => (
            <li key={w.week} className="rounded-2xl border border-border/60 bg-card p-4">
              <p className="text-xs font-semibold uppercase tracking-wider text-primary">
                Week {w.week}
              </p>
              <p className="mt-1 text-sm text-foreground">{w.action}</p>
            </li>
          ))}
        </ol>
      </Block>

      <Block title={`Closing note for ${name}`}>
        <Card>
          <p className="font-display text-lg italic text-foreground/90">
            {report.encouragement_to_student}
          </p>
          <p className="mt-3 text-xs text-muted-foreground">
            Reading this aloud in the meeting often grounds the conversation in the student's voice.
          </p>
        </Card>
      </Block>
    </>
  );
}

function Card({ title, children }: { title?: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-border/60 bg-card p-5">
      {title && (
        <h3 className="text-xs font-semibold uppercase tracking-wider text-primary">{title}</h3>
      )}
      <div className={title ? "mt-2" : ""}>{children}</div>
    </div>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-10 page-break">
      <h2 className="font-display text-2xl font-medium tracking-tight">{title}</h2>
      <div className="mt-4">{children}</div>
    </div>
  );
}

function BulletList({ items, compact = false }: { items: string[]; compact?: boolean }) {
  return (
    <ul
      className={cn(
        "space-y-2 leading-relaxed text-muted-foreground",
        compact ? "mt-1 text-sm" : "mt-2 text-sm",
      )}
    >
      {items.map((it, i) => (
        <li key={i} className="flex gap-2">
          <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
          <span>{it}</span>
        </li>
      ))}
    </ul>
  );
}
