/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FrameworkRouteImport } from './routes/framework'
import { Route as FamiliesRouteImport } from './routes/families'
import { Route as EducatorsRouteImport } from './routes/educators'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as PathwaysPathwayIdRouteImport } from './routes/pathways.$pathwayId'
import { Route as DemoReportRouteImport } from './routes/demo_.report'
import { Route as DemoIntakeRouteImport } from './routes/demo_.intake'
import { Route as DemoHubRouteImport } from './routes/demo_.hub'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPptPrepRouteImport } from './routes/_authenticated/ppt-prep'
import { Route as AuthenticatedPathwayRouteImport } from './routes/_authenticated/pathway'
import { Route as AuthenticatedPartnersManageRouteImport } from './routes/_authenticated/partners-manage'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminSchoolRouteImport } from './routes/_authenticated/admin-school'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedMeetingsMeetingIdRouteImport } from './routes/_authenticated/meetings.$meetingId'
import { Route as AuthenticatedFormsSlugRouteImport } from './routes/_authenticated/forms.$slug'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworkRoute = FrameworkRouteImport.update({
  id: '/framework',
  path: '/framework',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesRoute = FamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => rootRouteImport,
} as any)
const EducatorsRoute = EducatorsRouteImport.update({
  id: '/educators',
  path: '/educators',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysPathwayIdRoute = PathwaysPathwayIdRouteImport.update({
  id: '/pathways/$pathwayId',
  path: '/pathways/$pathwayId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReportRoute = DemoReportRouteImport.update({
  id: '/demo_/report',
  path: '/demo/report',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIntakeRoute = DemoIntakeRouteImport.update({
  id: '/demo_/intake',
  path: '/demo/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHubRoute = DemoHubRouteImport.update({
  id: '/demo_/hub',
  path: '/demo/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPptPrepRoute = AuthenticatedPptPrepRouteImport.update({
  id: '/ppt-prep',
  path: '/ppt-prep',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPathwayRoute = AuthenticatedPathwayRouteImport.update({
  id: '/pathway',
  path: '/pathway',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnersManageRoute =
  AuthenticatedPartnersManageRouteImport.update({
    id: '/partners-manage',
    path: '/partners-manage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSchoolRoute =
  AuthenticatedAdminSchoolRouteImport.update({
    id: '/admin-school',
    path: '/admin-school',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRoute =
  AuthenticatedMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => AuthenticatedMeetingsRoute,
  } as any)
const AuthenticatedFormsSlugRoute = AuthenticatedFormsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedFormsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/educators': typeof EducatorsRoute
  '/families': typeof FamiliesRoute
  '/framework': typeof FrameworkRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/waitlist': typeof WaitlistRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-school': typeof AuthenticatedAdminSchoolRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/partners-manage': typeof AuthenticatedPartnersManageRoute
  '/pathway': typeof AuthenticatedPathwayRoute
  '/ppt-prep': typeof AuthenticatedPptPrepRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/demo/hub': typeof DemoHubRoute
  '/demo/intake': typeof DemoIntakeRoute
  '/demo/report': typeof DemoReportRoute
  '/pathways/$pathwayId': typeof PathwaysPathwayIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/forms/$slug': typeof AuthenticatedFormsSlugRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/educators': typeof EducatorsRoute
  '/families': typeof FamiliesRoute
  '/framework': typeof FrameworkRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/waitlist': typeof WaitlistRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-school': typeof AuthenticatedAdminSchoolRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/forms': typeof AuthenticatedFormsRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/partners-manage': typeof AuthenticatedPartnersManageRoute
  '/pathway': typeof AuthenticatedPathwayRoute
  '/ppt-prep': typeof AuthenticatedPptPrepRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/demo/hub': typeof DemoHubRoute
  '/demo/intake': typeof DemoIntakeRoute
  '/demo/report': typeof DemoReportRoute
  '/pathways/$pathwayId': typeof PathwaysPathwayIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/forms/$slug': typeof AuthenticatedFormsSlugRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/demo': typeof DemoRoute
  '/educators': typeof EducatorsRoute
  '/families': typeof FamiliesRoute
  '/framework': typeof FrameworkRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-school': typeof AuthenticatedAdminSchoolRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRouteWithChildren
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/partners-manage': typeof AuthenticatedPartnersManageRoute
  '/_authenticated/pathway': typeof AuthenticatedPathwayRoute
  '/_authenticated/ppt-prep': typeof AuthenticatedPptPrepRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/demo_/hub': typeof DemoHubRoute
  '/demo_/intake': typeof DemoIntakeRoute
  '/demo_/report': typeof DemoReportRoute
  '/pathways/$pathwayId': typeof PathwaysPathwayIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/forms/$slug': typeof AuthenticatedFormsSlugRoute
  '/_authenticated/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo'
    | '/educators'
    | '/families'
    | '/framework'
    | '/login'
    | '/partners'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/research'
    | '/reset-password'
    | '/resources'
    | '/waitlist'
    | '/admin'
    | '/admin-school'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/feed'
    | '/forms'
    | '/goals'
    | '/insights'
    | '/meetings'
    | '/messages'
    | '/onboarding'
    | '/opportunities'
    | '/partners-manage'
    | '/pathway'
    | '/ppt-prep'
    | '/reports'
    | '/settings'
    | '/students'
    | '/demo/hub'
    | '/demo/intake'
    | '/demo/report'
    | '/pathways/$pathwayId'
    | '/share/$token'
    | '/forms/$slug'
    | '/meetings/$meetingId'
    | '/reports/$reportId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/educators'
    | '/families'
    | '/framework'
    | '/login'
    | '/partners'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/research'
    | '/reset-password'
    | '/resources'
    | '/waitlist'
    | '/admin'
    | '/admin-school'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/feed'
    | '/forms'
    | '/goals'
    | '/insights'
    | '/meetings'
    | '/messages'
    | '/onboarding'
    | '/opportunities'
    | '/partners-manage'
    | '/pathway'
    | '/ppt-prep'
    | '/reports'
    | '/settings'
    | '/students'
    | '/demo/hub'
    | '/demo/intake'
    | '/demo/report'
    | '/pathways/$pathwayId'
    | '/share/$token'
    | '/forms/$slug'
    | '/meetings/$meetingId'
    | '/reports/$reportId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/demo'
    | '/educators'
    | '/families'
    | '/framework'
    | '/login'
    | '/partners'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/research'
    | '/reset-password'
    | '/resources'
    | '/waitlist'
    | '/_authenticated/admin'
    | '/_authenticated/admin-school'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/feed'
    | '/_authenticated/forms'
    | '/_authenticated/goals'
    | '/_authenticated/insights'
    | '/_authenticated/meetings'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/opportunities'
    | '/_authenticated/partners-manage'
    | '/_authenticated/pathway'
    | '/_authenticated/ppt-prep'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/demo_/hub'
    | '/demo_/intake'
    | '/demo_/report'
    | '/pathways/$pathwayId'
    | '/share/$token'
    | '/_authenticated/forms/$slug'
    | '/_authenticated/meetings/$meetingId'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoRoute: typeof DemoRoute
  EducatorsRoute: typeof EducatorsRoute
  FamiliesRoute: typeof FamiliesRoute
  FrameworkRoute: typeof FrameworkRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  WaitlistRoute: typeof WaitlistRoute
  DemoHubRoute: typeof DemoHubRoute
  DemoIntakeRoute: typeof DemoIntakeRoute
  DemoReportRoute: typeof DemoReportRoute
  PathwaysPathwayIdRoute: typeof PathwaysPathwayIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/framework': {
      id: '/framework'
      path: '/framework'
      fullPath: '/framework'
      preLoaderRoute: typeof FrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families': {
      id: '/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educators': {
      id: '/educators'
      path: '/educators'
      fullPath: '/educators'
      preLoaderRoute: typeof EducatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways/$pathwayId': {
      id: '/pathways/$pathwayId'
      path: '/pathways/$pathwayId'
      fullPath: '/pathways/$pathwayId'
      preLoaderRoute: typeof PathwaysPathwayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/report': {
      id: '/demo_/report'
      path: '/demo/report'
      fullPath: '/demo/report'
      preLoaderRoute: typeof DemoReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/intake': {
      id: '/demo_/intake'
      path: '/demo/intake'
      fullPath: '/demo/intake'
      preLoaderRoute: typeof DemoIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/hub': {
      id: '/demo_/hub'
      path: '/demo/hub'
      fullPath: '/demo/hub'
      preLoaderRoute: typeof DemoHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ppt-prep': {
      id: '/_authenticated/ppt-prep'
      path: '/ppt-prep'
      fullPath: '/ppt-prep'
      preLoaderRoute: typeof AuthenticatedPptPrepRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pathway': {
      id: '/_authenticated/pathway'
      path: '/pathway'
      fullPath: '/pathway'
      preLoaderRoute: typeof AuthenticatedPathwayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partners-manage': {
      id: '/_authenticated/partners-manage'
      path: '/partners-manage'
      fullPath: '/partners-manage'
      preLoaderRoute: typeof AuthenticatedPartnersManageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-school': {
      id: '/_authenticated/admin-school'
      path: '/admin-school'
      fullPath: '/admin-school'
      preLoaderRoute: typeof AuthenticatedAdminSchoolRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/meetings/$meetingId': {
      id: '/_authenticated/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/forms/$slug': {
      id: '/_authenticated/forms/$slug'
      path: '/$slug'
      fullPath: '/forms/$slug'
      preLoaderRoute: typeof AuthenticatedFormsSlugRouteImport
      parentRoute: typeof AuthenticatedFormsRoute
    }
  }
}

interface AuthenticatedFormsRouteChildren {
  AuthenticatedFormsSlugRoute: typeof AuthenticatedFormsSlugRoute
}

const AuthenticatedFormsRouteChildren: AuthenticatedFormsRouteChildren = {
  AuthenticatedFormsSlugRoute: AuthenticatedFormsSlugRoute,
}

const AuthenticatedFormsRouteWithChildren =
  AuthenticatedFormsRoute._addFileChildren(AuthenticatedFormsRouteChildren)

interface AuthenticatedMeetingsRouteChildren {
  AuthenticatedMeetingsMeetingIdRoute: typeof AuthenticatedMeetingsMeetingIdRoute
}

const AuthenticatedMeetingsRouteChildren: AuthenticatedMeetingsRouteChildren = {
  AuthenticatedMeetingsMeetingIdRoute: AuthenticatedMeetingsMeetingIdRoute,
}

const AuthenticatedMeetingsRouteWithChildren =
  AuthenticatedMeetingsRoute._addFileChildren(
    AuthenticatedMeetingsRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminSchoolRoute: typeof AuthenticatedAdminSchoolRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRouteWithChildren
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedPartnersManageRoute: typeof AuthenticatedPartnersManageRoute
  AuthenticatedPathwayRoute: typeof AuthenticatedPathwayRoute
  AuthenticatedPptPrepRoute: typeof AuthenticatedPptPrepRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminSchoolRoute: AuthenticatedAdminSchoolRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRouteWithChildren,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedPartnersManageRoute: AuthenticatedPartnersManageRoute,
  AuthenticatedPathwayRoute: AuthenticatedPathwayRoute,
  AuthenticatedPptPrepRoute: AuthenticatedPptPrepRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoRoute: DemoRoute,
  EducatorsRoute: EducatorsRoute,
  FamiliesRoute: FamiliesRoute,
  FrameworkRoute: FrameworkRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  WaitlistRoute: WaitlistRoute,
  DemoHubRoute: DemoHubRoute,
  DemoIntakeRoute: DemoIntakeRoute,
  DemoReportRoute: DemoReportRoute,
  PathwaysPathwayIdRoute: PathwaysPathwayIdRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
