
INSERT INTO public.system_health_checks
  (key, label, category, status, route, backend_table, priority, sort_order,
   notes, action_needed, pass_criteria, fail_criteria, reference)
VALUES
  ('flow_student_onboarding','Student: sign-up → onboarding → student workspace','role_flows','working','/onboarding','profiles','high',700,
   'Onboarding role=student creates profile + student row; lands on /dashboard (student layout).',NULL,
   'New student lands on /dashboard with StudentDashboard and MyIepSummaryCard visible.','Lands on generic dashboard or onboarding loop.','src/routes/_authenticated/onboarding.tsx'),
  ('flow_student_workspace','Student: core workspace (voice, IEP summary, NBA)','role_flows','working','/dashboard','students','high',701,
   'StudentDashboard renders NextBestAction(surface=student), Student Voice, plain-language IEP summary.',NULL,
   'NBA, voice prompts, and My IEP card render for the signed-in student.','Empty dashboard, missing voice or IEP card.','src/components/dashboard/StudentDashboard.tsx'),
  ('flow_student_boundary','Student: cannot reach educator/admin areas','role_flows','working','/caseload','user_roles','critical',702,
   'RoleGuard on /caseload, /school/*, /district/*, /admin denies student audience and redirects to /dashboard.',NULL,
   'Direct nav to /caseload toasts "not available" and lands on /dashboard.','Student can view educator caseload or admin pages.','src/components/RoleGuard.tsx'),
  ('flow_family_onboarding','Family: sign-up → onboarding → first student','role_flows','working','/onboarding','students','high',710,
   'Parent/guardian onboarding creates first student in step 4 and lands on /dashboard.',NULL,
   'After onboarding, /dashboard shows the new student in the picker.','Parent stuck without a student or routed away from /dashboard.','src/lib/profile.functions.ts'),
  ('flow_family_workspace','Family: dashboard, IEP upload, Pathway report','role_flows','working','/dashboard','documents','high',711,
   'NextBestAction(surface=family) walks profile → voice → upload → report → action items.',NULL,
   'NBA advances the user through each milestone as data is added.','NBA never advances or shows wrong CTA for surface=family.','src/lib/next-best-action.functions.ts'),
  ('flow_family_boundary','Family: scoped to own/shared students','role_flows','working',NULL,'students','critical',712,
   'RLS can_access_student gates students, documents, reports; share tokens audience-scoped.',NULL,
   'A family user cannot read another family''s student row.','Cross-family data visible.','can_access_student SQL function'),
  ('flow_educator_onboarding','Educator: onboarding redirects to /caseload','role_flows','working','/caseload','student_collaborators','high',720,
   'Dashboard route detects educator audience and replaces to /caseload; fallbackPathFor agrees.',NULL,
   'New educator lands directly on /caseload after onboarding.','Educator stuck on /dashboard.','src/routes/_authenticated/dashboard.tsx'),
  ('flow_educator_workspace','Educator: caseload, document review, meeting prep','role_flows','working','/caseload','documents','high',721,
   'Caseload lists accepted student_collaborators; document review and /ppt-prep accessible.',NULL,
   'Educator can open any student they collaborate on and reach PPT prep.','Caseload empty for an educator with active invites.','src/routes/_authenticated/caseload.tsx'),
  ('flow_educator_boundary','Educator: blocked from district/admin hubs','role_flows','working','/district/overview','user_roles','high',722,
   'RoleGuard denies educator audience on /district/* and /admin.',NULL,
   'Deep-link to /district/overview redirects with toast.','Educator reaches district dashboards.','src/lib/role-policy.ts'),
  ('flow_school_onboarding','School Admin: onboarding → /school/overview','role_flows','working','/school/overview','organization_memberships','high',730,
   'fallbackPathFor returns /school/overview; dashboard auto-redirects school_admin.',NULL,
   'School admin lands on /school/overview after sign-in.','School admin lands on family dashboard.','src/lib/role-policy.ts'),
  ('flow_school_workspace','School Admin: overview, team, reports, implementation','role_flows','working','/school/overview','organizations','medium',731,
   'All four /school/* routes exist and are role-guarded.',NULL,
   'Nav tabs reach each /school/* page without permission error.','One or more /school/* tabs 404 or deny access.','src/routes/_authenticated/school.*.tsx'),
  ('flow_school_boundary','School Admin: cannot edit district workspace','role_flows','working','/district/overview','user_roles','high',732,
   'ROUTE_AUDIENCES restricts /district/* to district_admin + admin.',NULL,
   'Direct nav to /district/overview is denied for school_admin.','School admin can mutate district records.','src/lib/role-policy.ts'),
  ('flow_district_onboarding','District Admin: onboarding → /district/overview','role_flows','working','/district/overview','organization_memberships','high',740,
   'fallbackPathFor returns /district/overview; dashboard redirects district_admin.',NULL,
   'District admin lands on /district/overview after sign-in.','District admin stuck on family dashboard.','src/lib/role-policy.ts'),
  ('flow_district_workspace','District Admin: overview, schools, team, reports','role_flows','working','/district/overview','organizations','medium',741,
   'All four /district/* routes exist with DistrictNav + RoleGuard.',NULL,
   'All district tabs load with data scoped to the district.','Tabs missing or showing other-district data.','src/components/district/DistrictNav.tsx'),
  ('flow_district_boundary','District Admin: scoped to own district','role_flows','needs_attention',NULL,'organization_memberships','high',742,
   'Verify district queries filter on organization_memberships; cross-district leakage check needed.',
   'Add a focused RLS test for cross-district isolation similar to rls-demo-isolation.test.mjs.',
   'A district admin cannot read another district''s schools or rosters.','Cross-district data visible in any /district/* view.','tests/rls-demo-isolation.test.mjs'),
  ('flow_partner_onboarding','Partner: onboarding → /partners-manage','role_flows','working','/partners-manage','partner_organizations','high',750,
   'Partner role flows to /partners-manage via fallbackPathFor; dashboard redirects partners.',NULL,
   'Partner lands directly on /partners-manage post sign-in.','Partner lands on /dashboard or hits a permission error.','src/lib/role-policy.ts'),
  ('flow_partner_workspace','Partner: opportunities catalog + manage view','role_flows','working','/opportunities','partner_opportunities','medium',751,
   '/opportunities allowed for partner audience; /partners-manage is partner-only.',NULL,
   'Partner can browse opportunities and edit their own org listings.','Partner cannot reach the catalog or their own listings.','src/lib/role-policy.ts'),
  ('flow_partner_boundary','Partner: hard-blocked from IEP/transition docs','role_flows','working',NULL,'document_permissions','critical',752,
   'DocumentPermissionsDialog refuses partner audience grants for iep/transition-plan doc types.',NULL,
   'Permission dialog disables partner row with amber warning for IEP/transition documents.','Partner audience can be granted view on an IEP.','src/components/students/DocumentPermissionsDialog.tsx'),
  ('flow_admin_onboarding','Platform Admin: sign-in → /admin','role_flows','working','/admin','admin_roles','high',760,
   'fallbackPathFor returns /admin for admin audience; admin invite token claims platform role.',NULL,
   'Platform admin lands on /admin and sees Owner Hub.','Platform admin stuck on family dashboard.','src/routes/admin-invite.$token.tsx'),
  ('flow_admin_workspace','Platform Admin: full Owner Hub coverage','role_flows','working','/owner','admin_activity_logs','medium',761,
   '60+ owner.* routes cover analytics, content, compliance, health, partners, audits.',NULL,
   'Every owner.* route loads under is_platform_admin guard.','Owner route 404s or denies a real platform admin.','src/routes/_authenticated/owner.tsx'),
  ('flow_admin_boundary','Platform Admin: actions audited + role-separated','role_flows','needs_attention','/owner/activity','admin_activity_logs','high',762,
   'Verify every privileged owner action writes an admin_activity_logs row; some legacy paths may not.',
   'Sweep server fns under src/lib/owner/* and add admin_activity_logs.insert where missing.',
   'Every destructive admin action appears in /owner/activity within a few seconds.','Privileged action runs but is absent from the activity log.','src/lib/owner/')
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  category = EXCLUDED.category,
  status = EXCLUDED.status,
  route = EXCLUDED.route,
  backend_table = EXCLUDED.backend_table,
  priority = EXCLUDED.priority,
  sort_order = EXCLUDED.sort_order,
  notes = EXCLUDED.notes,
  action_needed = EXCLUDED.action_needed,
  pass_criteria = EXCLUDED.pass_criteria,
  fail_criteria = EXCLUDED.fail_criteria,
  reference = EXCLUDED.reference;
