/**
 * Realistic sample Next Actions for demo/workspace previews.
 * All CTA routes point to demo-safe pages so unauthenticated visitors
 * can click through the sample without hitting protected routes.
 */
import type { NextAction, ActivityEvent, NextActionRole } from "./types";

const now = () => new Date().toISOString();

function mk(base: Partial<NextAction> & Pick<NextAction, "id" | "kind" | "title" | "reason" | "ctaLabel" | "ctaRoute">): NextAction {
  return {
    ownerLabel: base.ownerLabel ?? "You",
    status: base.status ?? "not_started",
    urgency: base.urgency ?? "normal",
    priority: base.priority ?? 50,
    updatedAt: base.updatedAt ?? now(),
    ...base,
  } as NextAction;
}

export const DEMO_NEXT_ACTIONS: Record<NextActionRole, NextAction[]> = {
  student: [
    mk({
      id: "s-voice",
      kind: "complete_student_voice",
      title: "Finish Your Student Voice Prompts",
      reason: "3 of 8 prompts still open — your answers shape the Pathway Report your team reads.",
      ownerLabel: "You",
      ctaLabel: "Open Student Voice",
      ctaRoute: "/demo/voice",
      status: "in_progress",
      urgency: "due_soon",
      dueLabel: "Due In 4 Days",
      priority: 10,
    }),
    mk({
      id: "s-meeting",
      kind: "prepare_ppt",
      title: "Prepare For Your PPT Meeting",
      reason: "Review the agenda and add anything you want the team to hear.",
      ctaLabel: "Review Agenda",
      ctaRoute: "/demo/meeting",
      status: "needs_review",
      urgency: "due_soon",
      dueLabel: "Meeting In 6 Days",
      priority: 15,
    }),
    mk({
      id: "s-report",
      kind: "review_report",
      title: "Review Your Draft Pathway Report",
      reason: "New goals were suggested from your latest assessment.",
      ctaLabel: "Open Pathway Report",
      ctaRoute: "/demo/report",
      status: "needs_review",
      urgency: "normal",
      priority: 25,
    }),
    mk({
      id: "s-opp",
      kind: "explore_opportunities",
      title: "Explore 2 New Opportunities",
      reason: "Two culinary programs match your interests and IEP supports.",
      ctaLabel: "See Opportunities",
      ctaRoute: "/demo/opportunities",
      secondaryLabel: "Save For Later",
      secondaryRoute: "/demo/opportunities",
      priority: 40,
    }),
    mk({
      id: "s-goal",
      kind: "complete_evidence_upload",
      title: "Add Evidence For Goal 2",
      reason: "You said you were practicing bus routes — upload a photo or short note.",
      ctaLabel: "Add Evidence",
      ctaRoute: "/demo/plan",
      priority: 55,
    }),
  ],

  family: [
    mk({
      id: "f-consent",
      kind: "sign_consent",
      title: "Sign Sharing Consent For The Team",
      reason: "The case manager needs consent to share the new evaluation.",
      ctaLabel: "Review + Sign",
      ctaRoute: "/demo/family",
      status: "waiting",
      urgency: "overdue",
      dueLabel: "Overdue By 2 Days",
      priority: 5,
    }),
    mk({
      id: "f-upload",
      kind: "upload_iep",
      title: "Upload Latest IEP",
      reason: "Your last upload was 11 months ago — a fresh copy keeps the report accurate.",
      ctaLabel: "Upload Document",
      ctaRoute: "/demo/documents",
      urgency: "due_soon",
      dueLabel: "Due This Week",
      priority: 12,
    }),
    mk({
      id: "f-priorities",
      kind: "complete_family_priorities",
      title: "Complete Family Priorities Intake",
      reason: "Two sections still empty — this shapes what the team hears at the PPT.",
      ctaLabel: "Continue Intake",
      ctaRoute: "/demo/intake",
      status: "in_progress",
      priority: 20,
    }),
    mk({
      id: "f-meeting",
      kind: "confirm_meeting",
      title: "Confirm PPT Meeting Time",
      reason: "The school proposed Tuesday 3pm — accept or suggest another time.",
      ctaLabel: "Confirm Meeting",
      ctaRoute: "/demo/meeting",
      status: "needs_review",
      priority: 22,
    }),
    mk({
      id: "f-report",
      kind: "review_report_family",
      title: "Review The Pathway Report Draft",
      reason: "See what the team is proposing before the PPT.",
      ctaLabel: "Open Report",
      ctaRoute: "/demo/report",
      priority: 35,
    }),
  ],

  educator: [
    mk({
      id: "e-gaps",
      kind: "close_data_gaps",
      title: "Close 2 High-Priority Data Gaps",
      reason: "Two students are missing a current transition assessment before their PPT.",
      ownerLabel: "Case Manager",
      ctaLabel: "Open Data Gaps",
      ctaRoute: "/demo/educator",
      status: "in_progress",
      urgency: "due_soon",
      dueLabel: "This Week",
      priority: 5,
    }),
    mk({
      id: "e-docs",
      kind: "review_uploaded_documents",
      title: "Review 3 Newly Uploaded Documents",
      reason: "Families uploaded evaluations and progress reports awaiting your review.",
      ctaLabel: "Review Documents",
      ctaRoute: "/demo/documents",
      status: "needs_review",
      priority: 12,
    }),
    mk({
      id: "e-report",
      kind: "finalize_report",
      title: "Finalize Pathway Report For Marisol R.",
      reason: "Draft is complete — one goal needs a measurable target before you share it.",
      ctaLabel: "Open Report",
      ctaRoute: "/demo/report",
      status: "in_progress",
      urgency: "due_soon",
      dueLabel: "PPT In 3 Days",
      priority: 8,
    }),
    mk({
      id: "e-ppt",
      kind: "schedule_ppt",
      title: "Schedule 2 Overdue PPT Meetings",
      reason: "Annual review dates passed for 2 students on your caseload.",
      ctaLabel: "Open Calendar",
      ctaRoute: "/demo/calendar",
      urgency: "overdue",
      dueLabel: "Overdue",
      priority: 3,
    }),
    mk({
      id: "e-refer",
      kind: "refer_adult_services",
      title: "Refer 1 Senior To Adult Services",
      reason: "Consent is signed — send the referral so BRS/DDS can begin intake.",
      ctaLabel: "Send Referral",
      ctaRoute: "/demo/connection",
      priority: 25,
    }),
  ],

  school_admin: [
    mk({
      id: "sa-invite",
      kind: "invite_staff",
      title: "Invite 3 Case Managers",
      reason: "Three staff members haven't been added yet — they can't see caseloads until invited.",
      ownerLabel: "School Admin",
      ctaLabel: "Send Invites",
      ctaRoute: "/demo/school-admin",
      urgency: "due_soon",
      priority: 8,
    }),
    mk({
      id: "sa-readiness",
      kind: "review_readiness_gaps",
      title: "Review School Readiness Gaps",
      reason: "5 seniors show missing transition evidence 30 days before graduation.",
      ctaLabel: "Open Readiness",
      ctaRoute: "/demo/school-admin",
      status: "needs_review",
      priority: 12,
    }),
    mk({
      id: "sa-reports",
      kind: "check_report_completion",
      title: "Check Pathway Report Completion",
      reason: "62% of eligible students have a draft report — target is 90% before spring PPTs.",
      ctaLabel: "See Completion",
      ctaRoute: "/demo/school-admin",
      priority: 25,
    }),
    mk({
      id: "sa-access",
      kind: "resolve_access_issue",
      title: "Resolve 2 Access Requests",
      reason: "Family members are waiting on your approval to see student records.",
      ctaLabel: "Review Requests",
      ctaRoute: "/demo/school-admin",
      status: "waiting",
      urgency: "due_soon",
      priority: 10,
    }),
  ],

  district_admin: [
    mk({
      id: "da-rollout",
      kind: "review_rollout",
      title: "Review Spring Rollout Across 4 Schools",
      reason: "Two schools haven't completed staff onboarding yet.",
      ownerLabel: "District Admin",
      ctaLabel: "Open Rollout",
      ctaRoute: "/demo/district-admin",
      status: "in_progress",
      priority: 10,
    }),
    mk({
      id: "da-compliance",
      kind: "check_compliance",
      title: "Check District Compliance Signals",
      reason: "3 schools trending below target on transition-assessment completion.",
      ctaLabel: "See Compliance",
      ctaRoute: "/demo/district-admin",
      status: "needs_review",
      urgency: "due_soon",
      priority: 8,
    }),
    mk({
      id: "da-adoption",
      kind: "review_adoption",
      title: "Review Adoption Report",
      reason: "Weekly adoption digest is ready — share with leadership before Friday.",
      ctaLabel: "Open Report",
      ctaRoute: "/demo/district-admin",
      priority: 30,
    }),
    mk({
      id: "da-partner",
      kind: "approve_partner",
      title: "Approve 1 Partner Organization",
      reason: "New workforce partner is awaiting district sign-off.",
      ctaLabel: "Review Partner",
      ctaRoute: "/demo/partner",
      status: "waiting",
      priority: 20,
    }),
  ],

  partner: [
    mk({
      id: "p-publish",
      kind: "publish_opportunity",
      title: "Publish Draft Opportunity: Summer Culinary Program",
      reason: "Draft is complete — students can't see it until you publish.",
      ownerLabel: "Partner",
      ctaLabel: "Publish Now",
      ctaRoute: "/demo/opportunities",
      urgency: "due_soon",
      dueLabel: "Applications Open In 5 Days",
      priority: 8,
    }),
    mk({
      id: "p-matches",
      kind: "review_matches",
      title: "Review 4 Student Matches",
      reason: "Case managers referred 4 students for your Spring cohort.",
      ctaLabel: "Review Matches",
      ctaRoute: "/demo/opportunities",
      status: "needs_review",
      priority: 12,
    }),
    mk({
      id: "p-profile",
      kind: "complete_partner_profile",
      title: "Complete Partner Profile",
      reason: "Add mentor bios and site logistics — schools use this to place students.",
      ctaLabel: "Edit Profile",
      ctaRoute: "/demo/partner",
      status: "in_progress",
      priority: 22,
    }),
    mk({
      id: "p-avail",
      kind: "confirm_availability",
      title: "Confirm Fall Availability",
      reason: "Schools plan placements 6 weeks out — confirm your fall capacity.",
      ctaLabel: "Update Availability",
      ctaRoute: "/demo/opportunities",
      priority: 35,
    }),
  ],

  admin: [
    mk({
      id: "a-waitlist",
      kind: "review_waitlist",
      title: "Review 8 Waitlist Requests",
      reason: "New signups awaiting district approval or trial provisioning.",
      ownerLabel: "Platform Admin",
      ctaLabel: "Open Waitlist",
      ctaRoute: "/demo/owner",
      status: "needs_review",
      urgency: "due_soon",
      priority: 8,
    }),
    mk({
      id: "a-partners",
      kind: "approve_partners",
      title: "Approve 3 Partner Submissions",
      reason: "New partners are ready to publish opportunities once approved.",
      ctaLabel: "Review Partners",
      ctaRoute: "/demo/partner",
      priority: 15,
    }),
    mk({
      id: "a-health",
      kind: "check_platform_health",
      title: "Check Platform Health Signals",
      reason: "One system-health check is warning — investigate before it becomes user-visible.",
      ctaLabel: "Open Health",
      ctaRoute: "/demo/owner",
      status: "waiting",
      urgency: "due_soon",
      priority: 10,
    }),
    mk({
      id: "a-billing",
      kind: "review_billing",
      title: "Review Billing Readiness",
      reason: "Two districts have trials ending in the next 14 days.",
      ctaLabel: "See Billing",
      ctaRoute: "/demo/owner",
      priority: 25,
    }),
  ],
};

export const DEMO_RECENTLY_COMPLETED: Record<NextActionRole, NextAction[]> = {
  student: [
    mk({
      id: "sc-1",
      kind: "complete_student_voice",
      title: "Answered 5 Student Voice Prompts",
      reason: "Great work — the team can already see your answers.",
      ctaLabel: "View",
      ctaRoute: "/demo/voice",
      status: "completed",
      completedAt: now(),
    }),
  ],
  family: [
    mk({
      id: "fc-1",
      kind: "upload_iep",
      title: "Uploaded Current IEP",
      reason: "Shared with the case manager.",
      ctaLabel: "View Document",
      ctaRoute: "/demo/documents",
      status: "completed",
      completedAt: now(),
    }),
  ],
  educator: [
    mk({
      id: "ec-1",
      kind: "finalize_report",
      title: "Finalized Pathway Report For J. Nguyen",
      reason: "Shared with family + student.",
      ctaLabel: "View Report",
      ctaRoute: "/demo/report",
      status: "completed",
      completedAt: now(),
    }),
  ],
  school_admin: [],
  district_admin: [],
  partner: [
    mk({
      id: "pc-1",
      kind: "publish_opportunity",
      title: "Published Winter Externship",
      reason: "Now visible to case managers district-wide.",
      ctaLabel: "View",
      ctaRoute: "/demo/opportunities",
      status: "completed",
      completedAt: now(),
    }),
  ],
  admin: [],
};

export const DEMO_ACTIVITY_HISTORY: Record<NextActionRole, ActivityEvent[]> = {
  student: [
    { id: "sh-1", eventType: "step_completed", actorLabel: "You", subjectTitle: "Answered 5 Student Voice prompts", subjectRoute: "/demo/voice", occurredAt: now() },
    { id: "sh-2", eventType: "report_updated", actorLabel: "Ms. Rivera (Case Manager)", subjectTitle: "Added a new goal to your Pathway Report", subjectRoute: "/demo/report", occurredAt: now() },
    { id: "sh-3", eventType: "meeting_noted", actorLabel: "Your Team", subjectTitle: "Scheduled PPT meeting for next Tuesday", subjectRoute: "/demo/meeting", occurredAt: now() },
  ],
  family: [
    { id: "fh-1", eventType: "upload", actorLabel: "You", subjectTitle: "Uploaded current IEP (2025)", subjectRoute: "/demo/documents", occurredAt: now() },
    { id: "fh-2", eventType: "access_changed", actorLabel: "You", subjectTitle: "Granted sharing access to Ms. Rivera", occurredAt: now() },
    { id: "fh-3", eventType: "comment", actorLabel: "Ms. Rivera", subjectTitle: "Left a note on the transition plan", subjectRoute: "/demo/plan", occurredAt: now() },
  ],
  educator: [
    { id: "eh-1", eventType: "report_updated", actorLabel: "You", subjectTitle: "Updated Pathway Report for A. Chen", subjectRoute: "/demo/report", occurredAt: now() },
    { id: "eh-2", eventType: "meeting_noted", actorLabel: "You", subjectTitle: "Logged PPT meeting notes for M. Rivera", subjectRoute: "/demo/meeting", occurredAt: now() },
    { id: "eh-3", eventType: "upload", actorLabel: "Family of J. Park", subjectTitle: "Uploaded new evaluation", subjectRoute: "/demo/documents", occurredAt: now() },
  ],
  school_admin: [
    { id: "sah-1", eventType: "invitation_sent", actorLabel: "You", subjectTitle: "Invited 2 new case managers", occurredAt: now() },
    { id: "sah-2", eventType: "access_changed", actorLabel: "You", subjectTitle: "Approved family access for 4 students", occurredAt: now() },
  ],
  district_admin: [
    { id: "dah-1", eventType: "report_updated", actorLabel: "System", subjectTitle: "Weekly district adoption digest ready", occurredAt: now() },
    { id: "dah-2", eventType: "access_changed", actorLabel: "You", subjectTitle: "Approved new school onboarding", occurredAt: now() },
  ],
  partner: [
    { id: "ph-1", eventType: "opportunity_status", actorLabel: "You", subjectTitle: "Published Winter Externship", subjectRoute: "/demo/opportunities", occurredAt: now() },
    { id: "ph-2", eventType: "invitation_accepted", actorLabel: "Case Manager M. Rivera", subjectTitle: "Referred 2 students to your program", occurredAt: now() },
  ],
  admin: [
    { id: "ah-1", eventType: "invitation_accepted", actorLabel: "New District", subjectTitle: "Accepted platform invitation", occurredAt: now() },
    { id: "ah-2", eventType: "opportunity_status", actorLabel: "Partner Org", subjectTitle: "Submitted new partner profile for review", occurredAt: now() },
  ],
};

/** Convenience: get the top N active demo actions for a role, sorted. */
export function getDemoActive(role: NextActionRole, limit = 5): NextAction[] {
  return DEMO_NEXT_ACTIONS[role].slice(0, limit);
}
